name: CI Github Pages
on:
  #监听push操作 ，这里只配置了main分支，所以只有推送main分支才会触发以下任务
  push:
    branches:
      - master 
jobs:
  # 任务ID
  build-and-deploy:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      
      - name: 将代码拉取到虚拟机
        uses: actions/checkout@v3

      - name: 检出代码仓库中的代码，并将代码复制到工作流程的执行环境中
        uses: actions/checkout@v2

      - name: 安装nodejs18.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: 安装依赖&构建
        run: |
          npm install
          npm run build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: vite-build-src #部署后提交到那个分支
          folder: dist #这里填打包好的目录名称
